/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PostsCommentsRouteImport } from './routes/posts/comments'
import { Route as PostsIdRouteImport } from './routes/posts/$id'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCommentsRoute = PostsCommentsRouteImport.update({
  id: '/posts/comments',
  path: '/posts/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/posts': typeof PostsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/comments': typeof PostsCommentsRoute
}
export interface FileRoutesByTo {
  '/posts': typeof PostsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/comments': typeof PostsCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/posts': typeof PostsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/comments': typeof PostsCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/posts' | '/posts/$id' | '/posts/comments'
  fileRoutesByTo: FileRoutesByTo
  to: '/posts' | '/posts/$id' | '/posts/comments'
  id: '__root__' | '/posts' | '/posts/$id' | '/posts/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PostsRoute: typeof PostsRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsCommentsRoute: typeof PostsCommentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/comments': {
      id: '/posts/comments'
      path: '/posts/comments'
      fullPath: '/posts/comments'
      preLoaderRoute: typeof PostsCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PostsRoute: PostsRoute,
  PostsIdRoute: PostsIdRoute,
  PostsCommentsRoute: PostsCommentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
