/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root'
import { Route as layoutsPostsLayoutRouteImport } from './routes/layouts/postsLayout'
import { Route as postsRouteImport } from './routes/posts'
import { Route as postsIdRouteImport } from './routes/posts-id'

const layoutsPostsLayoutRoute = layoutsPostsLayoutRouteImport.update({
  id: '/_postsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const postsRoute = postsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => layoutsPostsLayoutRoute,
} as any)
const postsIdRoute = postsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => postsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/posts': typeof postsRouteWithChildren
  '/posts/$id': typeof postsIdRoute
}
export interface FileRoutesByTo {
  '/posts': typeof postsRouteWithChildren
  '/posts/$id': typeof postsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_postsLayout': typeof layoutsPostsLayoutRouteWithChildren
  '/_postsLayout/posts': typeof postsRouteWithChildren
  '/_postsLayout/posts/$id': typeof postsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/posts' | '/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/posts' | '/posts/$id'
  id:
    | '__root__'
    | '/_postsLayout'
    | '/_postsLayout/posts'
    | '/_postsLayout/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutsPostsLayoutRoute: typeof layoutsPostsLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_postsLayout': {
      id: '/_postsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutsPostsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_postsLayout/posts': {
      id: '/_postsLayout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof postsRouteImport
      parentRoute: typeof layoutsPostsLayoutRoute
    }
    '/_postsLayout/posts/$id': {
      id: '/_postsLayout/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof postsIdRouteImport
      parentRoute: typeof postsRoute
    }
  }
}

interface postsRouteChildren {
  postsIdRoute: typeof postsIdRoute
}

const postsRouteChildren: postsRouteChildren = {
  postsIdRoute: postsIdRoute,
}

const postsRouteWithChildren = postsRoute._addFileChildren(postsRouteChildren)

interface layoutsPostsLayoutRouteChildren {
  postsRoute: typeof postsRouteWithChildren
}

const layoutsPostsLayoutRouteChildren: layoutsPostsLayoutRouteChildren = {
  postsRoute: postsRouteWithChildren,
}

const layoutsPostsLayoutRouteWithChildren =
  layoutsPostsLayoutRoute._addFileChildren(layoutsPostsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  layoutsPostsLayoutRoute: layoutsPostsLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
